# Generated by Django 6.0.4 on 2026-05-01 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=127)),
                ('cpf', models.CharField(max_length=14)),
                ('nascimento', models.DateTimeField()),
                ('pretensao_salarial', models.DecimalField(decimal_places=2, max_digits=7)),
                ('experiencia', models.TextField()),
                ('escolaridade', models.CharField(choices=[('ENSINO_FUNDAMENTAL', 'Ensino fundamental'), ('ENSINO_MEDIO', 'Ensino médio'), ('TECNOLOGO', 'Tecnólogo'), ('ENSINO_SUPERIOR', 'Ensino Superior'), ('POS_MBA_MESTRADO', 'Pós / MBA / Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=31)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=127)),
                ('nome_fantasia', models.CharField(max_length=127)),
                ('cnpj', models.CharField(max_length=14)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('faixa_salarial', models.CharField(choices=[('ATE_MIL', 'Até R$ 1.000,00'), ('DE_MIL_A_DOIS_MIL', 'De R$ 1.000,00 à R$ 2.000,00'), ('DE_DOIS_MIL_A_TRES_MIL', 'De R$ 2.000,00 à R$ 3.000,00'), ('ACIMA_DE_TRES_MIL', 'Acima de R$ 3.000,00')], max_length=31)),
                ('requisitos', models.TextField()),
                ('escolaridade_exigida', models.CharField(choices=[('ENSINO_FUNDAMENTAL', 'Ensino fundamental'), ('ENSINO_MEDIO', 'Ensino médio'), ('TECNOLOGO', 'Tecnólogo'), ('ENSINO_SUPERIOR', 'Ensino Superior'), ('POS_MBA_MESTRADO', 'Pós / MBA / Mestrado'), ('DOUTORADO', 'Doutorado')], max_length=31)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Candidatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.candidato')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.vaga')),
            ],
        ),
    ]
